### ISSUE TITLE
The weights of positive and negative terms of CSD used for text-to-3D generation

### ISSUE THREAD

**Issue by lizhiqi49** [CVMI-Lab/Classifier-Score-Distillation#1]
I didn't see the description in paper, or I missed it. Can you tell me?

**Comment by lingtengqiu** [comment]
> I didn't see the description in paper, or I missed it. Can you tell me?

maybe https://xinyu-andy.github.io/Classifier-Score-Distillation/ ?

**Comment by lizhiqi49** [comment]
I mean the two hyper-parameters, $\omega_1$ and $\omega_2$ in equation (10) of the paper. I didn't see the corresponding description of them for text-to-3D generation either in paper or the project page.

**Comment by lingtengqiu** [comment]
> I mean the two hyper-parameters, $\omega_1$ and $\omega_2$ in equation (10) of the paper. I didn't see the corresponding description of them for text-to-3D generation either in paper or the project page.

The details can be found in ICLR2024, openreviewer. I saw the author provide the link attached to partial CSD codes.

**Comment by lizhiqi49** [comment]
> The details can be found in ICLR2024, openreviewer. I saw the author provide the link attached to partial CSD codes.

I found it, thank you!
